export const colors = {
  snow: 'white',
  clear: 'rgba(0, 0, 0, 0.0)',
  blur: 'rgba(0, 0, 0, 0.27)',
  blurRed: '#e54d3e',
  blurGreen: '#27ae61',
  blurYellow: '#f1c40f',
  blurBricky: '#e67f22',
  drawer: '#373445',
  dark: '#12132c',
  txtDark: '#3d3d3d',
  darkGreen: 'rgb(34, 94, 65)',
  green: '#27ae61',
  yellowishOrange: '#ffa50b',
  red: '#e54d3e',
  gray: '#EAEAEA',
  blueGrey: '#a6a7bd',
  warmGrey: '#afafaf',
  lightGrey: '#ccd3db',
  darkGreyBlue: 'rgb(41, 34, 103)',
  sunYellow: '#f3da22',
  redTwo: '#e30804',
  black: '#2b2b2b',
  blackTwo: '#4a4a4a',
  lightBlack: '#747474',
  white: '#f2f2f2',
  whiteTwo: '#e7e7e7',
  whiteThree: '#d8d8d8',
  whiteFour: 'rgba(255, 255, 255, 0.9)',
  fakeLight: 'rgba(0, 0, 0, 0.3)',
  fake: 'rgba(0, 0, 0, 0.5)',
  fakeDark: 'rgba(0, 0, 0, 0.7)',
  lightRed: '#F64C4C',
  lightBlue: '#324269',
  blueTwo: '#336BDE',
  textBlue: '#2E4168',
  background: 'white',
  divider: '#eeeeee',
  primaryDark: '#303F9F',
  primaryColor: '#0088E5',
  primaryLightColor: '#0088FF',
  secondaryColor: '#294067',
  grey: '#A7A7A7',
  textGrey: '#666666',
  darkGrey: '#909090',
  darkBlue: 'rgb(46, 65, 104)',
  darkBlueTwo: 'rgb(60, 114, 207)',
  blurGrey: '#bababa',
};
export const TYPE_GROUPS = ['HELP', 'EMERGENCY', 'REPORT'];
export const STATUS = [
  {
    id: '_OPEN',
    color: colors.blurRed,
    text: {
      vi: 'Đang đợi giúp đỡ',
      en: 'Open',
    },
  },
  {
    id: '_INPROGRESS',
    color: colors.blurYellow,
    text: {
      vi: 'Đang tiến hành',
      en: 'Open',
    },
  },
  {
    id: '_CLOSED',
    color: colors.warmGrey,
    text: {
      vi: 'Đóng',
      en: 'Closed',
    },
  },
  {
    id: '_EXPIRED',
    color: colors.warmGrey,
    text: {
      vi: 'Hết hạn',
      en: 'Expired',
    },
  },
  {
    id: '_RESOLVED',
    color: colors.blurGreen,
    text: {
      vi: 'Đã giải quyết',
      en: 'Resolved',
    },
  },
  {
    id: '_CANCELLED',
    color: colors.warmGrey,
    text: {
      vi: 'Đã huỷ',
      en: 'Cancelled',
    },
  },
];
